### ISSUE TITLE
Brew version

### ISSUE THREAD

**Issue by deimosfr** [lintingzhen/commitizen-go#1]
Hi,

Thanks for your commitizen go version!

It would be great if you could make a brew package for it :)

Thanks

**Comment by ivorscott** [comment]
+1

**Comment by lintingzhen** [comment]
> Hi,
> 
> Thanks for your commitizen go version!
> 
> It would be great if you could make a brew package for it :)
> 
> Thanks

 好的，谢谢 @deimosfr 的建议，我研究一下怎么提交到brew上。

**Comment by deimosfr** [comment]
Thanks

**Comment by lintingzhen** [comment]
support installation with homebrew.
```
$ brew tap lintingzhen/tap
$ brew install commitizen-go
$ sudo commitizen --install
```

**Comment by deimosfr** [comment]
Thanks a lot :)
