### ISSUE TITLE
`git cz` could silently fail

### ISSUE THREAD

**Issue by skaurus** [lintingzhen/commitizen-go#15]
If some pre-commit hook prevents creating a commit (in my case it was a hook checking that commit message starts from lowercase letter), then commit would not be created;`git cz` though would appear as if it was successful.

**Comment by deimosfr** [comment]
same issue on my side. Would be great to have pre-commit logs as well, they are hidden

**Comment by lintingzhen** [comment]
This is a serious bug, I have fixed it, thank you both.
@skaurus @deimosfr

**Comment by lintingzhen** [comment]
solved.
