### ISSUE TITLE
Add support for custom configuration

### ISSUE THREAD

**Issue by nickylogan** [lintingzhen/commitizen-go#3]
I've finally found an equivalent of commitizen for Golang projects. Just wondering, are there any plans to add custom configuration files? (as a reference, [cz-cli](https://github.com/commitizen/cz-cli) has support for `.czrc` files)

**Comment by lintingzhen** [comment]
I have had this plan, but I have no well-formed demand.
You can put it forward if you have a need, and then I will see how to achieve it.

**Comment by lintingzhen** [comment]
> I've finally found an equivalent of commitizen for Golang projects. Just wondering, are there any plans to add custom configuration files? (as a reference, [cz-cli](https://github.com/commitizen/cz-cli) has support for `.czrc` files)

A version that supports custom configuration of commit message has been released, enjoy it and please let me know if you have any questions.

**Comment by nickylogan** [comment]
Thanks for the update! I'll take a look at the new feature :). In the meantime, I'll just close the issue 👍 .
