### ISSUE TITLE
Problem Installing via Brew

### ISSUE THREAD

**Issue by DeFrakt** [lintingzhen/commitizen-go#4]
`brew tap lintingzhen/tap` - works

`brew install commitizen-go`
==> Installing commitizen-go from lintingzhen/tap
==> Downloading https://github.com/lintingzhen/commitizen-go/releases/download/v1.0.0/commitizen-Darwin-x86-1.0.0.tgz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/178145467/2a250a00-e728-11ea-89c8-9c07047e2d2b?X-Amz-Algorithm=AW
######################################################################## 100.0%
Error: An exception occurred within a child process:
 Errno::ENOENT: No such file or directory - commitizen

Is brew pointing to a bad version?

**Comment by lintingzhen** [comment]
Oh, yes, there is a mistake in my homebrew-tap!
I have fixed it and you can try again.

**Comment by DeFrakt** [comment]
Thank you for the timely update 👍  All works.
